export const actionAuthor = {
    // cán bộ
    PHAN_QUYEN_CAN_BO: ["ALL_CANBO_PHANQUYEN", "CANBO_PHANQUYEN"],
    XEM_CAN_BO_ALL: ["ALL_CANBO_XEM"],
    XEM_CAN_BO_DV: ["CANBO_XEM"],
    THEM_MOI_CAN_BO_ALL: ["ALL_CANBO_CAPNHAT"],
    THEM_MOI_CAN_BO_DV: ["CANBO_CAPNHAT"],
    // sinh viên
    XEM_SINH_VIEN_ALL: ["ALL_SINHVIEN_XEM"],
    XEM_SINH_VIEN_DV: ["SINHVIEN_XEM"],
    THEM_MOI_SINH_VIEN_ALL: ["ALL_SINHVIEN_CAPNHAT"],
    THEM_MOI_SINH_VIEN_DV: ["SINHVIEN_CAPNHAT"],
    //tải ảnh
    CAP_NHAT_ANH_CHO_SV_ALL: ["ALL_ALBUM_CAPNHAT"],
    CAP_NHAT_ANH_CHO_SV_DV: ["ALBUM_CAPNHAT"],
    // bài viết tin tức
    CAP_NHAT_TIN_BAI_ALL: ["ALL_TINBAI_CAPNHAT"],
    CAP_NHAT_TIN_BAI_DV: ["TINBAI_CAPNHAT"],
    XEM_TIN_BAI_ALL: ["ALL_TINBAI_XEM"],
    XEM_TIN_BAI_DV: ["TINBAI_XEM"],
    DUYET_TIN_BAI: ["TINBAI_DUYET"],
    HUY_XUAT_BAN_TIN_BAI: ["TINBAI_HUY_XUATBAN"],
    XUAT_BAN_TIN_BAI: ["TINBAI_XUATBAN"],
    // bản đồ số
    CAP_NHAT_VA_THEM_BAN_DO: ["BANDO_CAPNHAT"],
    XOA_BAN_DO: ["BANDO_XOA"],
    // loại bản đồ
    CAP_NHAT_VA_THEM_LOAI_BAN_DO: ["LOAI_BANDO_CAPNHAT"],
    XOA_LOAI_BAN_DO: ["LOAI_BANDO_XOA"],
    // thêm file
    THEM_NGUOI_DUNG: ["IMPORT_USER"],
    // Nhà trọ
    ALL_NHATRO_CAPNHAT: ["ALL_NHATRO_CAPNHAT"],
    ALL_NHATRO_XEM: ["ALL_NHATRO_XEM"],
    NHATRO_CAPNHAT: ["NHATRO_CAPNHAT"],
    NHATRO_XEM: ["NHATRO_XEM"]
}