export const titlePage = {
    ManageCadres: "Quản Lý Cán Bộ",
    MangeRightsGroup: "Quản Lý Nhóm Quyền",
    ManageMenu: "Quản Lý Menu",
    ManageStudents: "Quản Lý Sinh Viên",
    ManageNews: "Quản Lý Tin Tức",
    ManageCategoryNews: "Quản Lý Chuyên Mục Tin Tức",
    ManageFeedback: "Quản Lý Trả Lời Góp Ý",
    ManageMap: "Quản Lý Địa Điểm Bản Đồ",
    CamNangHoaLac: "Cẩm Nang Hòa Lạc",
    ManageTypeMap: "Quản Lý Loại Bản Đồ",
    ManageArea: "Quản Lý Khu Vực Bản Đồ",
    ManageMotelInfor: "Quản Lý Thông Tin Nhà Trọ",
    ManageListMotel: "Quản Lý Dánh Sách Nhà Trọ",
    ManageHandBook: "Quản Lý Cẩm Nang Hòa Lạc",
    ManageTypeHandBook: "Quản Lý Chuyên Mục Cẩm Nang Hòa Lạc",
    camNangHoaLac: "Chi Tiết Cẩm Nang Hòa Lạc",
    ManageNotification: "Xem Danh Sách Thông Báo",
}